package com.nms.common;

public enum AuditEventType {
    NOTIFICATION_ACCEPTED,
    NOTIFICATION_REJECTED,
    NOTIFICATION_DEDUPLICATED,
    ROUTING_DECIDED,
    DELIVERY_QUEUED,
    DELIVERY_ATTEMPTED,
    DELIVERY_SUCCEEDED,
    DELIVERY_FAILED,
    RETRY_SCHEDULED,
    DELIVERY_EXHAUSTED,
    NOTIFICATION_EXPIRED
}
